apiVersion: v1
kind: Pod
metadata:
  name: soft-affinity
  labels:
    app: node-affinity-soft-pod
spec:
  containers:
    - name: node-affinity-soft-pod
      image: wangyanglinux/myapp:v1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-node03