apiVersion: v1
kind: Pod
metadata:
  name: test-pd-host-path
spec:
  containers:
    - image: wangyanglinux/myapp:v2
      name: test-container
      volumeMounts:
        - mountPath: /test-pd-host-path-demo
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate

#        type: DirectoryOrCreate 才可以, 否则报错