apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: label-node
  name: label-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: label-node
  template:
    metadata:
      labels:
        app: label-node
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: label-con
        image: wangyanglinux/myapp:v1
        ports:
        - containerPort: 80